language: cpp
compiler: clang
dist: xenial

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt update -qq
  # Doxygen is used for documentation
  - sudo apt install -qq python3-pip python3-setuptools python3-venv
  - source ./tools/set_env
  - source ./tools/activate_venv
  - pip3 install --upgrade -r requirements.txt
  - conan config install https://github.com/ManuelMeraz/conan-config.git

install:
  # C++17
  - sudo apt install -qq g++-7 clang-6.0

script:
  - ./tools/build.py -pr clang60-debug
