language: cpp
compiler: clang
dist: xenial

before_install:
  - sudo apt update -qq 
  - sudo apt install -qq python3-pip python3-setuptools python3-venv -y
  - source ./tools/set_env
  - source ./tools/activate_venv

install:
  - pip3 install --upgrade -r requirements.txt
  - conan config install https://github.com/ManuelMeraz/conan-config.git

script:
  - ./tools/build.py -pr clang70
  - cd build && make test

