#!/usr/bin/env bash

if [ -z $TRACKER_PROJECT ]; then
  echo "Please source the set_env script in the scripts/ directory to"
  echo "set the \$TRACKER_PROJECT environment variable, which keeps track of"
  echo "the project directory."
  return 1
fi

VENV_NAME=${1:-tracker_venv}

if [ ! -d $TRACKER_PROJECT/$VENV_NAME ]; then
  python3 -m venv $TRACKER_PROJECT/$VENV_NAME
else
  echo "directory exists"
fi
# shellcheck source=/dev/null
source "$VENV_NAME/bin/activate"
